// Custom Service Worker push handler.
// This file is injected into the Service Worker generated by @ducanh2912/next-pwa
// via the customWorkerDir option in next.config.mjs.
// NOTE: This runs in a ServiceWorkerGlobalScope; all self.* calls are valid here.

var _self = self;

// Ensure the SW takes control immediately.
_self.addEventListener("install", function () {
  _self.skipWaiting();
});

_self.addEventListener("activate", function (event) {
  event.waitUntil(_self.clients.claim());
});

// ─── Push Event ───────────────────────────────────────────────────────────────
_self.addEventListener("push", function (event) {
  if (!event.data) {
    console.warn("[SW] Push event without data payload.");
    return;
  }

  try {
    var data = event.data.json();

    var title = data.title || "Andes Pilates";
    var options = {
      body: data.body || "",
      icon: data.icon || "/andes_logo_pwa.png",
      badge: data.badge || "/andes_logo_pwa.png",
      data: {
        url: data.url || "/",
      },
      vibrate: [100, 50, 100],
      tag: data.tag || "studio-notification",
      renotify: true,
      requireInteraction: false,
    };

    event.waitUntil(_self.registration.showNotification(title, options));
  } catch (err) {
    console.error("[SW] Error processing push event:", err);
  }
});

// ─── Notification Click ───────────────────────────────────────────────────────
_self.addEventListener("notificationclick", function (event) {
  event.notification.close();

  var url = event.notification.data && event.notification.data.url || "/";

  event.waitUntil(
    _self.clients
      .matchAll({ type: "window", includeUncontrolled: true })
      .then(function (clientList) {
        for (var i = 0; i < clientList.length; i++) {
          var client = clientList[i];
          if (client.url.indexOf(_self.location.origin) !== -1 && "focus" in client) {
            client.focus();
            client.postMessage({ type: "NOTIFICATION_CLICK", url: url });
            return;
          }
        }
        if (_self.clients.openWindow) {
          return _self.clients.openWindow(url);
        }
      })
  );
});
